import React from "react";

export const metadata = {
  title: "Al-malaki | Home",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return <div>{children}</div>;
};

export default layout;
